package com.workworth.workday.application;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
import com.workworth.workday.domain.*;
import com.workworth.workday.exception.WorkdayConflictException;
import com.workworth.workday.exception.WorkdayIntervalValidationException;
import com.workworth.workday.persistence.*;
import java.time.*; import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.test.util.ReflectionTestUtils;
import org.mockito.ArgumentCaptor;

class WorkdayServiceTest {
 private WorkdayRepository workdays=mock(WorkdayRepository.class); private MealBreakRepository breaks=mock(MealBreakRepository.class); private PartialAbsenceRepository absences=mock(PartialAbsenceRepository.class); private WorkdayTimeCorrectionRepository corrections=mock(WorkdayTimeCorrectionRepository.class); private final List<MealBreak> breakList=new ArrayList<>(); private final List<PartialAbsence> absenceList=new ArrayList<>();
 private Clock clock; private WorkdayService service; private ApplicationEventPublisher events=mock(ApplicationEventPublisher.class);
 @BeforeEach void init(){clock=Clock.fixed(Instant.parse("2026-07-06T08:00:00Z"),ZoneId.of("Europe/Madrid")); service=new WorkdayService(workdays,breaks,absences,corrections,new EconomicTimeCalculator(),clock,"Europe/Madrid",events); when(breaks.findByWorkdayIdOrderByStartedAt(any())).thenAnswer(x->breakList); when(absences.findByWorkdayIdOrderByStartedAt(any())).thenAnswer(x->absenceList); when(breaks.save(any())).thenAnswer(x->{MealBreak b=x.getArgument(0);breakList.add(b);return b;}); when(absences.save(any())).thenAnswer(x->{PartialAbsence a=x.getArgument(0);absenceList.add(a);return a;}); when(corrections.save(any())).thenAnswer(x->{WorkdayTimeCorrection correction=x.getArgument(0);ReflectionTestUtils.setField(correction,"id",99L);return correction;}); }
 private Workday day(LocalDate date){var s=WorkdaySchedule.forDate(date).orElseThrow();return new Workday(date,"Europe/Madrid",s.variant(),s.start(),s.end(),s.maximumEconomicTime().getSeconds(),clock.instant());}
 private void existing(Workday d){ReflectionTestUtils.setField(d,"id",1L);when(workdays.findLockedByLocalDate(d.getLocalDate())).thenReturn(Optional.of(d));}
 @Test void rejectsPausePauseAndPauseAbsenceOverlaps(){var d=day(LocalDate.of(2026,7,6));existing(d); service.startMealBreak(d.getLocalDate()); assertThatThrownBy(()->service.startMealBreak(d.getLocalDate())).isInstanceOf(WorkdayConflictException.class); breakList.clear(); absenceList.add(new PartialAbsence(d,Instant.parse("2026-07-06T07:00:00Z"),Instant.parse("2026-07-06T09:00:00Z"),null)); assertThatThrownBy(()->service.startMealBreak(d.getLocalDate())).isInstanceOf(WorkdayIntervalValidationException.class);}
 @Test void rejectsAbsenceAbsenceOverlapAndAllowsUpdate(){var d=day(LocalDate.of(2026,7,6));existing(d); var first=service.addAbsence(d.getLocalDate(),Instant.parse("2026-07-06T07:00:00Z"),Instant.parse("2026-07-06T08:00:00Z"),"doctor"); ReflectionTestUtils.setField(first,"id",2L); assertThatThrownBy(()->service.addAbsence(d.getLocalDate(),Instant.parse("2026-07-06T07:30:00Z"),Instant.parse("2026-07-06T08:30:00Z"),null)).isInstanceOf(WorkdayIntervalValidationException.class); when(absences.findById(first.getId())).thenReturn(Optional.of(first)); service.updateAbsence(d.getLocalDate(),first.getId(),Instant.parse("2026-07-06T09:00:00Z"),Instant.parse("2026-07-06T10:00:00Z"),"updated"); assertThat(first.getReason()).isEqualTo("updated");}
 @Test void reconcilesStatesCancelsAndAutoClosesBreak(){var scheduled=day(LocalDate.of(2026,7,7));existing(scheduled);assertThat(service.reconcile(scheduled.getLocalDate()).getStatus()).isEqualTo(WorkdayStatus.SCHEDULED);service.cancel(scheduled.getLocalDate(),"holiday");assertThat(scheduled.getStatus()).isEqualTo(WorkdayStatus.CANCELLED); var active=day(LocalDate.of(2026,7,6));existing(active);service.cancel(active.getLocalDate(),"holiday");assertThat(active.getStatus()).isEqualTo(WorkdayStatus.CANCELLED); var done=day(LocalDate.of(2026,7,3));existing(done);breakList.add(new MealBreak(done,Instant.parse("2026-07-03T12:00:00Z")));service.reconcile(done.getLocalDate());assertThat(done.getStatus()).isEqualTo(WorkdayStatus.COMPLETED);assertThat(breakList.get(0).isEndedAutomatically()).isTrue();service.cancel(done.getLocalDate(),"holiday");assertThat(done.getStatus()).isEqualTo(WorkdayStatus.CANCELLED);}
 @Test void reconcilesSameDateIdempotently(){var d=day(LocalDate.of(2026,7,6));existing(d);assertThat(service.reconcile(d.getLocalDate())).isSameAs(service.reconcile(d.getLocalDate()));verify(workdays,never()).save(any());}
 @Test void amendsOnlyClosedBreaksOnCompletedWorkdaysAndRecordsAudit(){var completed=day(LocalDate.of(2026,7,3));existing(completed);var breakToAmend=new MealBreak(completed,Instant.parse("2026-07-03T08:00:00Z"));breakToAmend.end(Instant.parse("2026-07-03T09:00:00Z"),true);ReflectionTestUtils.setField(breakToAmend,"id",2L);breakList.add(breakToAmend);when(breaks.findById(2L)).thenReturn(Optional.of(breakToAmend));service.amendHistoricalMealBreak(completed.getLocalDate(),2L,Instant.parse("2026-07-03T07:00:00Z"),Instant.parse("2026-07-03T09:00:00Z"));var captured=ArgumentCaptor.forClass(WorkdayTimeCorrection.class);verify(corrections).save(captured.capture());assertThat(captured.getValue().getCause()).isEqualTo(WorkdayTimeCorrectionCause.MEAL_BREAK_CHANGED);assertThat(captured.getValue().getMealBreak()).isSameAs(breakToAmend);assertThat(captured.getValue().getPreviousBreakStartedAt()).isEqualTo(Instant.parse("2026-07-03T08:00:00Z"));assertThat(captured.getValue().getNewBreakStartedAt()).isEqualTo(Instant.parse("2026-07-03T07:00:00Z"));assertThat(captured.getValue().getPreviousBreakEndedAutomatically()).isTrue();assertThat(breakToAmend.isEndedAutomatically()).isFalse();verify(events).publishEvent(any(WorkdayTimeCorrectionRegisteredEvent.class));}
 @Test void rejectsHistoricalBreakAmendmentsForAllNonCompletedStates(){var scheduled=day(LocalDate.of(2026,7,7));existing(scheduled);assertThatThrownBy(()->service.amendHistoricalMealBreak(scheduled.getLocalDate(),2L,Instant.EPOCH,Instant.EPOCH.plusSeconds(1))).isInstanceOf(WorkdayConflictException.class);var active=day(LocalDate.of(2026,7,6));existing(active);assertThatThrownBy(()->service.amendHistoricalMealBreak(active.getLocalDate(),2L,Instant.EPOCH,Instant.EPOCH.plusSeconds(1))).isInstanceOf(WorkdayConflictException.class);breakList.add(new MealBreak(active,Instant.parse("2026-07-06T08:00:00Z")));assertThatThrownBy(()->service.amendHistoricalMealBreak(active.getLocalDate(),2L,Instant.EPOCH,Instant.EPOCH.plusSeconds(1))).isInstanceOf(WorkdayConflictException.class);var cancelled=day(LocalDate.of(2026,7,3));cancelled.cancel("holiday",clock.instant());existing(cancelled);assertThatThrownBy(()->service.amendHistoricalMealBreak(cancelled.getLocalDate(),2L,Instant.EPOCH,Instant.EPOCH.plusSeconds(1))).isInstanceOf(WorkdayConflictException.class);}
 @Test void rejectsInvalidOutOfWindowAndOverlappingHistoricalBreakAmendments(){var completed=day(LocalDate.of(2026,7,3));existing(completed);var target=new MealBreak(completed,Instant.parse("2026-07-03T07:00:00Z"));target.end(Instant.parse("2026-07-03T08:00:00Z"),false);ReflectionTestUtils.setField(target,"id",2L);breakList.add(target);when(breaks.findById(2L)).thenReturn(Optional.of(target));assertThatThrownBy(()->service.amendHistoricalMealBreak(completed.getLocalDate(),2L,Instant.parse("2026-07-03T08:00:00Z"),Instant.parse("2026-07-03T07:00:00Z"))).isInstanceOf(WorkdayIntervalValidationException.class);assertThatThrownBy(()->service.amendHistoricalMealBreak(completed.getLocalDate(),2L,Instant.parse("2026-07-03T05:00:00Z"),Instant.parse("2026-07-03T07:00:00Z"))).isInstanceOf(WorkdayIntervalValidationException.class);var other=new MealBreak(completed,Instant.parse("2026-07-03T09:00:00Z"));other.end(Instant.parse("2026-07-03T10:00:00Z"),false);ReflectionTestUtils.setField(other,"id",3L);breakList.add(other);assertThatThrownBy(()->service.amendHistoricalMealBreak(completed.getLocalDate(),2L,Instant.parse("2026-07-03T08:30:00Z"),Instant.parse("2026-07-03T09:30:00Z"))).isInstanceOf(WorkdayIntervalValidationException.class);breakList.remove(other);absenceList.add(new PartialAbsence(completed,Instant.parse("2026-07-03T09:00:00Z"),Instant.parse("2026-07-03T10:00:00Z"),null));assertThatThrownBy(()->service.amendHistoricalMealBreak(completed.getLocalDate(),2L,Instant.parse("2026-07-03T08:30:00Z"),Instant.parse("2026-07-03T09:30:00Z"))).isInstanceOf(WorkdayIntervalValidationException.class);}
}
