package com.workworth.earnings.application;
import static org.assertj.core.api.Assertions.assertThat; import static org.mockito.Mockito.*;
import com.workworth.earnings.domain.*; import com.workworth.earnings.persistence.*; import java.math.*; import java.time.*; import java.util.*; import org.junit.jupiter.api.*;
import com.workworth.preferences.application.ApplicationCurrencyProvider; import com.workworth.preferences.domain.ApplicationCurrency;
class EarningPeriodServiceTest {WorkdayEarningRepository earnings=mock(WorkdayEarningRepository.class);EarningCorrectionRepository corrections=mock(EarningCorrectionRepository.class); ApplicationCurrencyProvider applicationCurrency=mock(ApplicationCurrencyProvider.class); EarningPeriodService service; @BeforeEach void set(){when(applicationCurrency.currentCurrency()).thenReturn(ApplicationCurrency.EUR);service=new EarningPeriodService(earnings,corrections,Clock.fixed(Instant.parse("2026-01-01T12:00:00Z"),ZoneId.of("Europe/Madrid")),"Europe/Madrid",applicationCurrency);}
 WorkdayEarning earning(long id,String date,String amount){var e=mock(WorkdayEarning.class);when(e.getId()).thenReturn(id);when(e.getLocalDate()).thenReturn(LocalDate.parse(date));when(e.getStatus()).thenReturn(EarningStatus.AVAILABLE);when(e.getRawAmount()).thenReturn(new BigDecimal(amount));when(e.getCurrencyCode()).thenReturn("EUR");when(corrections.findByEarningIdOrderBySequenceDesc(id)).thenReturn(List.of());return e;}
 @Test void aggregatesTodayWeekMonthAndAllTimeWithOneRounding(){var a=earning(1,"2026-01-01","1.005000000000");var b=earning(2,"2025-12-31","2.005000000000");when(earnings.findAll()).thenReturn(List.of(a,b));assertThat(service.summarize(EarningPeriod.TODAY).publicAmount()).isEqualByComparingTo("1.01");assertThat(service.summarize(EarningPeriod.WEEK).internalAmount()).isEqualByComparingTo("3.010000000000");assertThat(service.summarize(EarningPeriod.MONTH).publicAmount()).isEqualByComparingTo("1.01");assertThat(service.summarize(EarningPeriod.ALL_TIME).publicAmount()).isEqualByComparingTo("3.01");}
 @Test void usesLatestCorrectionAndIgnoresUnavailableWhenAvailableEarningsExist(){var a=earning(1,"2025-12-29","10");var correction=mock(EarningCorrection.class);when(correction.getNewAmount()).thenReturn(new BigDecimal("4.500000000000"));when(corrections.findByEarningIdOrderBySequenceDesc(1L)).thenReturn(List.of(correction));var unavailable=unavailable("2025-12-29");when(earnings.findAll()).thenReturn(List.of(a,unavailable));var summary=service.summarize(EarningPeriod.WEEK);assertThat(summary.status()).isEqualTo(EarningStatus.AVAILABLE);assertThat(summary.publicAmount()).isEqualByComparingTo("4.50");}
 @Test void returnsUnavailableWhenOnlyUnavailableEarningsExist(){var unavailable=unavailable("2025-12-29");when(earnings.findAll()).thenReturn(List.of(unavailable));var summary=service.summarize(EarningPeriod.WEEK);assertThat(summary.status()).isEqualTo(EarningStatus.UNAVAILABLE);assertThat(summary.internalAmount()).isNull();assertThat(summary.publicAmount()).isNull();assertThat(summary.currencyCode()).isNull();}
 @Test void evaluatesEachContextIndependently(){var todayUnavailable=unavailable("2026-01-01");var weeklyAvailable=earning(1,"2025-12-29","8");when(earnings.findAll()).thenReturn(List.of(todayUnavailable,weeklyAvailable));assertThat(service.summarize(EarningPeriod.TODAY).status()).isEqualTo(EarningStatus.UNAVAILABLE);assertThat(service.summarize(EarningPeriod.WEEK).publicAmount()).isEqualByComparingTo("8.00");assertThat(service.summarize(EarningPeriod.MONTH).status()).isEqualTo(EarningStatus.UNAVAILABLE);assertThat(service.summarize(EarningPeriod.ALL_TIME).publicAmount()).isEqualByComparingTo("8.00");}
 @Test void returnsAnAvailableZeroForAnEmptyPeriod(){when(earnings.findAll()).thenReturn(List.of());var summary=service.summarize(EarningPeriod.ALL_TIME);assertThat(summary.status()).isEqualTo(EarningStatus.AVAILABLE);assertThat(summary.publicAmount()).isZero();assertThat(summary.currencyCode()).isEqualTo("EUR");}
 WorkdayEarning unavailable(String date){var e=mock(WorkdayEarning.class);when(e.getLocalDate()).thenReturn(LocalDate.parse(date));when(e.getStatus()).thenReturn(EarningStatus.UNAVAILABLE);return e;}
}
