package com.workworth.common.exception;

public enum ApiErrorCode {
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    SALARY_PROFILE_CONFLICT,
    SALARY_RATE_UNAVAILABLE,
    SALARY_CONFIGURATION_INCOMPLETE,
    APPLICATION_CURRENCY_LOCKED,
    GOAL_CONFLICT,
    GOAL_PROGRESS_UNAVAILABLE,
    GOAL_CURRENCY_MISMATCH,
    STATISTICS_CURRENCY_MISMATCH,
    REWARD_CONFLICT,
    REWARD_CURRENCY_MISMATCH,
    WORKDAY_CONFLICT,
    WORKDAY_INTERVAL_INVALID
}
